<a href="https://colab.research.google.com/github/sadot04/Inteligencia_artificial/blob/main/StudentsDeep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from re import X
# 0 imports
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
#import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

df = pd.read_csv("student_exam_scores.csv")

In [ ]:
df.isnull().sum()

student_id            0
hours_studied         0
sleep_hours           0
attendance_percent    0
previous_scores       0
exam_score            0
dtype: int64

In [ ]:
df

,student_id,hours_studied,sleep_hours,attendance_percent,previous_scores,exam_score
0,S001,8.0,8.8,72.1,45,30.2
1,S002,1.3,8.6,60.7,55,25.0
2,S003,4.0,8.2,73.7,86,35.8
3,S004,3.5,4.8,95.1,66,34.0
4,S005,9.1,6.4,89.8,71,40.3
...,...,...,...,...,...,...
195,S196,10.5,5.4,94.0,87,42.7
196,S197,7.1,6.1,85.1,92,40.4
197,S198,1.6,6.9,63.8,76,28.2
198,S199,12.0,7.3,50.5,58,42.0
199,S200,10.2,6.3,97.4,68,37.8

In [ ]:
print("Shape brute:", df.shape)
print("Cols:", list(df.columns))

Shape brute: (200, 6)
Cols: ['student_id', 'hours_studied', 'sleep_hours', 'attendance_percent', 'previous_scores', 'exam_score']

In [ ]:
SEED= 42
os.environ["PYTHONHASHSEED"] = str(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

In [ ]:
X = df[[
    "hours_studied", "sleep_hours", "attendance_percent", "previous_scores"
]].copy()

In [ ]:
y = df["exam_score"].astype(float).values

In [ ]:
num_cols= ["hours_studied", "sleep_hours", "attendance_percent", "previous_scores"]

En X fueron seleccionadas las variables de hours_studied, sleep_hours, attendance_percent y previous score porque consideramos que son importantes y relevantes a la hora de predecir el exam_score que es la variable objetivo en este dataset

In [ ]:
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [ ]:
from sklearn.pipeline import Pipeline
preprocess = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, num_cols),
    ],
    remainder = "drop"
)

In [ ]:
X_train_df, X_test_df, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=SEED
)
# Ajustar transformadores en train y transformar ambos

X_train = preprocess.fit_transform(X_train_df)
X_test = preprocess.transform(X_test_df)

X_train = X_train.astype(np.float32)
X_test = X_test.astype(np.float32)

print("Input dims:", X_train.shape[1])

Input dims: 4

In [ ]:
def build_model(input_dim: int) -> tf.keras.Model:
    model = models.Sequential([
        layers.Input(shape=(input_dim,)),
        layers.Dense(32, activation="relu"),
        layers.Dropout(0.20),
        layers.Dense(128, activation="relu"),
        layers.Dropout(0.20),
        layers.Dense(164, activation="relu"),
        layers.Dropout(0.20),
        layers.Dense(1)


    ])
    model.compile(
        optimizer="adam",
        loss="mse",
        metrics=["mae", tf.keras.metrics.RootMeanSquaredError(name="rmse")]
    )
    return model

model = build_model(X_train.shape[1])
model.summary()

Model: "sequential_31"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_110 (Dense)               │ (None, 32)             │           160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_79 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_111 (Dense)               │ (None, 128)            │         4,224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_80 (Dropout)            │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_112 (Dense)               │ (None, 164)            │        21,156 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_81 (Dropout)            │ (None, 164)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_113 (Dense)               │ (None, 1)              │           165 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 25,705 (100.41 KB)

 Trainable params: 25,705 (100.41 KB)

 Non-trainable params: 0 (0.00 B)

En este caso lo hicimos con 4 capas , una capa que tiene 32 neuorunas, la otra que tiene 128 neuronas, otra que tiene 164 neuronas y otra que tiene 1 sola neurona , esta decision fue debido que con estos cambios realizados nos lanzaba un mejor porcentaje en R^2 donde el mayor resultado que obtuvimos fue de 0.79 , ademas le pusimos un dropout para que el modelo no memorice los datos, ademas de que para el test fue implementado 0.2 de los datos y el 0.8 para el entrenamiento

In [ ]:
cbs = [
    callbacks.EarlyStopping(monitor="val_loss", mode="min", patience=12,
                            restore_best_weights=True),
    callbacks.ModelCheckpoint("weather_best.keras", monitor="val_loss", mode="min",
                              save_best_only=True),
    callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=6)
]

In [ ]:
hist = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=200,
    batch_size=32,
    callbacks=cbs,
    verbose=1
)

Epoch 1/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 1155.8922 - mae: 33.4004 - rmse: 33.9960 - val_loss: 1192.8080 - val_mae: 33.7881 - val_rmse: 34.5371 - learning_rate: 0.0010
Epoch 2/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 1115.1251 - mae: 32.7635 - rmse: 33.3904 - val_loss: 1152.8663 - val_mae: 33.1695 - val_rmse: 33.9539 - learning_rate: 0.0010
Epoch 3/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 1065.8546 - mae: 31.9887 - rmse: 32.6440 - val_loss: 1101.3757 - val_mae: 32.3482 - val_rmse: 33.1870 - learning_rate: 0.0010
Epoch 4/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 997.4445 - mae: 30.8587 - rmse: 31.5775 - val_loss: 1032.4490 - val_mae: 31.2051 - val_rmse: 32.1317 - learning_rate: 0.0010
Epoch 5/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 922.9811 - mae: 29.5216 - rmse: 30.3743 - val_loss: 942.5880 - val_mae: 29.6307 - val_rmse: 30.7016 - learning_rate: 0.0010
Epoch 6/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 824.4909 - mae: 27.7211 - rmse: 28.7067 - val_loss: 830.9319 - val_mae: 27.5158 - val_rmse: 28.8259 - learning_rate: 0.0010
Epoch 7/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 687.5788 - mae: 24.9911 - rmse: 26.2090 - val_loss: 698.6621 - val_mae: 24.7109 - val_rmse: 26.4322 - learning_rate: 0.0010
Epoch 8/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 542.1874 - mae: 21.4757 - rmse: 23.2653 - val_loss: 553.8092 - val_mae: 21.0865 - val_rmse: 23.5332 - learning_rate: 0.0010
Epoch 9/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 405.1616 - mae: 18.0835 - rmse: 20.1083 - val_loss: 414.2248 - val_mae: 17.3079 - val_rmse: 20.3525 - learning_rate: 0.0010
Epoch 10/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 275.7846 - mae: 14.5051 - rmse: 16.5915 - val_loss: 306.6106 - val_mae: 14.6672 - val_rmse: 17.5103 - learning_rate: 0.0010
Epoch 11/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 199.7868 - mae: 11.6813 - rmse: 14.1291 - val_loss: 245.4600 - val_mae: 13.4942 - val_rmse: 15.6672 - learning_rate: 0.0010
Epoch 12/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 188.4087 - mae: 11.3795 - rmse: 13.7209 - val_loss: 213.0590 - val_mae: 12.4998 - val_rmse: 14.5965 - learning_rate: 0.0010
Epoch 13/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 187.1063 - mae: 11.2642 - rmse: 13.6785 - val_loss: 184.5403 - val_mae: 11.5157 - val_rmse: 13.5846 - learning_rate: 0.0010
Epoch 14/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 149.4368 - mae: 9.9214 - rmse: 12.2211 - val_loss: 160.3774 - val_mae: 10.4578 - val_rmse: 12.6640 - learning_rate: 0.0010
Epoch 15/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 116.8198 - mae: 8.6718 - rmse: 10.8064 - val_loss: 146.4152 - val_mae: 9.8355 - val_rmse: 12.1002 - learning_rate: 0.0010
Epoch 16/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 98.3765 - mae: 7.8017 - rmse: 9.9137 - val_loss: 139.0512 - val_mae: 9.5530 - val_rmse: 11.7920 - learning_rate: 0.0010
Epoch 17/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 117.4474 - mae: 8.7498 - rmse: 10.8360 - val_loss: 131.3860 - val_mae: 9.2145 - val_rmse: 11.4624 - learning_rate: 0.0010
Epoch 18/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 81.7267 - mae: 7.3542 - rmse: 9.0371 - val_loss: 120.8461 - val_mae: 8.8328 - val_rmse: 10.9930 - learning_rate: 0.0010
Epoch 19/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 94.5383 - mae: 7.7167 - rmse: 9.7021 - val_loss: 109.8490 - val_mae: 8.4123 - val_rmse: 10.4809 - learning_rate: 0.0010
Epoch 20/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 91.7871 - mae: 7.6097 - rmse: 9.5754 - val_loss: 102.6561 - val_mae: 8.0955 - val_rmse: 10.1319 - learning_rate: 0.0010
Epoch 21/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 99.2621 - mae: 8.0331 - rmse: 9.9465 - val_loss: 93.6424 - val_mae: 7.7252 - val_rmse: 9.6769 - learning_rate: 0.0010
Epoch 22/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 80.9148 - mae: 7.0266 - rmse: 8.9830 - val_loss: 86.9120 - val_mae: 7.4514 - val_rmse: 9.3227 - learning_rate: 0.0010
Epoch 23/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 74.7930 - mae: 7.2521 - rmse: 8.6426 - val_loss: 80.3151 - val_mae: 7.1730 - val_rmse: 8.9619 - learning_rate: 0.0010
Epoch 24/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 77.0591 - mae: 7.3669 - rmse: 8.7603 - val_loss: 75.2841 - val_mae: 6.9451 - val_rmse: 8.6766 - learning_rate: 0.0010
Epoch 25/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 75.9857 - mae: 7.1747 - rmse: 8.7152 - val_loss: 72.2963 - val_mae: 6.8153 - val_rmse: 8.5027 - learning_rate: 0.0010
Epoch 26/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 65.9189 - mae: 6.5653 - rmse: 8.1097 - val_loss: 68.3391 - val_mae: 6.6304 - val_rmse: 8.2667 - learning_rate: 0.0010
Epoch 27/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 68.5674 - mae: 6.5552 - rmse: 8.2671 - val_loss: 66.7492 - val_mae: 6.5488 - val_rmse: 8.1700 - learning_rate: 0.0010
Epoch 28/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 71.9681 - mae: 7.0395 - rmse: 8.4670 - val_loss: 65.1870 - val_mae: 6.4557 - val_rmse: 8.0738 - learning_rate: 0.0010
Epoch 29/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 70.8572 - mae: 6.7099 - rmse: 8.3993 - val_loss: 60.8094 - val_mae: 6.2241 - val_rmse: 7.7980 - learning_rate: 0.0010
Epoch 30/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 74.0683 - mae: 6.9464 - rmse: 8.6039 - val_loss: 54.4694 - val_mae: 5.8665 - val_rmse: 7.3803 - learning_rate: 0.0010
Epoch 31/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 69.7455 - mae: 7.0676 - rmse: 8.3445 - val_loss: 50.1167 - val_mae: 5.6007 - val_rmse: 7.0793 - learning_rate: 0.0010
Epoch 32/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 63.3985 - mae: 6.5029 - rmse: 7.9600 - val_loss: 50.1916 - val_mae: 5.6344 - val_rmse: 7.0846 - learning_rate: 0.0010
Epoch 33/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 57.5121 - mae: 6.0660 - rmse: 7.5832 - val_loss: 50.0037 - val_mae: 5.6310 - val_rmse: 7.0713 - learning_rate: 0.0010
Epoch 34/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 71.7974 - mae: 7.1480 - rmse: 8.4693 - val_loss: 49.1909 - val_mae: 5.5751 - val_rmse: 7.0136 - learning_rate: 0.0010
Epoch 35/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 50.6565 - mae: 5.8079 - rmse: 7.1060 - val_loss: 46.2197 - val_mae: 5.3850 - val_rmse: 6.7985 - learning_rate: 0.0010
Epoch 36/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 54.9790 - mae: 6.2306 - rmse: 7.3993 - val_loss: 42.1682 - val_mae: 5.1641 - val_rmse: 6.4937 - learning_rate: 0.0010
Epoch 37/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 65.1041 - mae: 6.3142 - rmse: 8.0676 - val_loss: 40.8460 - val_mae: 5.1022 - val_rmse: 6.3911 - learning_rate: 0.0010
Epoch 38/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 58.2061 - mae: 6.2106 - rmse: 7.6284 - val_loss: 40.5350 - val_mae: 5.0980 - val_rmse: 6.3667 - learning_rate: 0.0010
Epoch 39/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 60.8904 - mae: 6.0974 - rmse: 7.8027 - val_loss: 39.7526 - val_mae: 5.0607 - val_rmse: 6.3050 - learning_rate: 0.0010
Epoch 40/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 49.7762 - mae: 5.7383 - rmse: 7.0374 - val_loss: 38.4356 - val_mae: 4.9838 - val_rmse: 6.1996 - learning_rate: 0.0010
Epoch 41/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 45.0820 - mae: 5.4173 - rmse: 6.6956 - val_loss: 38.2243 - val_mae: 4.9619 - val_rmse: 6.1826 - learning_rate: 0.0010
Epoch 42/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 43.4932 - mae: 5.1500 - rmse: 6.5897 - val_loss: 37.5706 - val_mae: 4.9230 - val_rmse: 6.1295 - learning_rate: 0.0010
Epoch 43/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 48.0695 - mae: 5.5075 - rmse: 6.9315 - val_loss: 36.0665 - val_mae: 4.8300 - val_rmse: 6.0055 - learning_rate: 0.0010
Epoch 44/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 47.5932 - mae: 5.5222 - rmse: 6.8915 - val_loss: 33.8163 - val_mae: 4.7169 - val_rmse: 5.8152 - learning_rate: 0.0010
Epoch 45/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 49.7161 - mae: 5.8093 - rmse: 7.0469 - val_loss: 33.4651 - val_mae: 4.7013 - val_rmse: 5.7849 - learning_rate: 0.0010
Epoch 46/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 50.2376 - mae: 5.7981 - rmse: 7.0808 - val_loss: 31.8977 - val_mae: 4.6232 - val_rmse: 5.6478 - learning_rate: 0.0010
Epoch 47/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 48.7858 - mae: 5.5858 - rmse: 6.9774 - val_loss: 31.2965 - val_mae: 4.5935 - val_rmse: 5.5943 - learning_rate: 0.0010
Epoch 48/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 43.6447 - mae: 5.3147 - rmse: 6.5983 - val_loss: 30.1526 - val_mae: 4.5310 - val_rmse: 5.4911 - learning_rate: 0.0010
Epoch 49/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 49.2941 - mae: 5.8275 - rmse: 7.0193 - val_loss: 29.9852 - val_mae: 4.5194 - val_rmse: 5.4759 - learning_rate: 0.0010
Epoch 50/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 51.6554 - mae: 5.7204 - rmse: 7.1704 - val_loss: 30.6544 - val_mae: 4.5488 - val_rmse: 5.5366 - learning_rate: 0.0010
Epoch 51/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 51.1399 - mae: 5.8918 - rmse: 7.1491 - val_loss: 30.7327 - val_mae: 4.5579 - val_rmse: 5.5437 - learning_rate: 0.0010
Epoch 52/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 41.4264 - mae: 5.2461 - rmse: 6.4360 - val_loss: 27.4146 - val_mae: 4.3786 - val_rmse: 5.2359 - learning_rate: 0.0010
Epoch 53/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 52.7088 - mae: 5.6677 - rmse: 7.2556 - val_loss: 24.6610 - val_mae: 4.1974 - val_rmse: 4.9660 - learning_rate: 0.0010
Epoch 54/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 40.6720 - mae: 4.9104 - rmse: 6.3671 - val_loss: 24.1525 - val_mae: 4.1467 - val_rmse: 4.9145 - learning_rate: 0.0010
Epoch 55/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 45.4645 - mae: 5.5484 - rmse: 6.7347 - val_loss: 24.3184 - val_mae: 4.1507 - val_rmse: 4.9314 - learning_rate: 0.0010
Epoch 56/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 43.0593 - mae: 5.3044 - rmse: 6.5540 - val_loss: 24.0265 - val_mae: 4.1251 - val_rmse: 4.9017 - learning_rate: 0.0010
Epoch 57/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 53.1311 - mae: 5.7662 - rmse: 7.2848 - val_loss: 25.1340 - val_mae: 4.1912 - val_rmse: 5.0134 - learning_rate: 0.0010
Epoch 58/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 41.0092 - mae: 5.1895 - rmse: 6.3999 - val_loss: 25.7592 - val_mae: 4.2359 - val_rmse: 5.0754 - learning_rate: 0.0010
Epoch 59/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 36.3042 - mae: 4.7513 - rmse: 6.0035 - val_loss: 24.0420 - val_mae: 4.1240 - val_rmse: 4.9033 - learning_rate: 0.0010
Epoch 60/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 38.8279 - mae: 5.2528 - rmse: 6.2212 - val_loss: 22.1277 - val_mae: 3.9796 - val_rmse: 4.7040 - learning_rate: 0.0010
Epoch 61/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 41.0815 - mae: 5.2432 - rmse: 6.4090 - val_loss: 22.3488 - val_mae: 3.9969 - val_rmse: 4.7275 - learning_rate: 0.0010
Epoch 62/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 40.8849 - mae: 5.2321 - rmse: 6.3930 - val_loss: 21.3574 - val_mae: 3.9107 - val_rmse: 4.6214 - learning_rate: 0.0010
Epoch 63/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 36.4365 - mae: 4.6973 - rmse: 6.0081 - val_loss: 22.6454 - val_mae: 4.0244 - val_rmse: 4.7587 - learning_rate: 0.0010
Epoch 64/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 34.6528 - mae: 4.6891 - rmse: 5.8714 - val_loss: 26.7499 - val_mae: 4.2969 - val_rmse: 5.1720 - learning_rate: 0.0010
Epoch 65/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 30.7037 - mae: 4.5500 - rmse: 5.5380 - val_loss: 30.0662 - val_mae: 4.4903 - val_rmse: 5.4833 - learning_rate: 0.0010
Epoch 66/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 39.2373 - mae: 5.0881 - rmse: 6.2636 - val_loss: 25.8733 - val_mae: 4.2273 - val_rmse: 5.0866 - learning_rate: 0.0010
Epoch 67/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 46.3021 - mae: 5.6576 - rmse: 6.8030 - val_loss: 20.0895 - val_mae: 3.8362 - val_rmse: 4.4821 - learning_rate: 0.0010
Epoch 68/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 43.0133 - mae: 5.4283 - rmse: 6.5569 - val_loss: 17.6437 - val_mae: 3.5962 - val_rmse: 4.2004 - learning_rate: 0.0010
Epoch 69/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 42.5589 - mae: 5.1335 - rmse: 6.5183 - val_loss: 17.8085 - val_mae: 3.6003 - val_rmse: 4.2200 - learning_rate: 0.0010
Epoch 70/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 35.3544 - mae: 4.6678 - rmse: 5.9446 - val_loss: 19.1644 - val_mae: 3.7190 - val_rmse: 4.3777 - learning_rate: 0.0010
Epoch 71/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 36.6383 - mae: 4.8023 - rmse: 6.0512 - val_loss: 20.2948 - val_mae: 3.8100 - val_rmse: 4.5050 - learning_rate: 0.0010
Epoch 72/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 34.1821 - mae: 4.7788 - rmse: 5.8437 - val_loss: 21.4942 - val_mae: 3.8982 - val_rmse: 4.6362 - learning_rate: 0.0010
Epoch 73/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 37.4201 - mae: 4.8849 - rmse: 6.1077 - val_loss: 21.0263 - val_mae: 3.8695 - val_rmse: 4.5854 - learning_rate: 0.0010
Epoch 74/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 26.4850 - mae: 4.1500 - rmse: 5.1441 - val_loss: 18.8057 - val_mae: 3.6884 - val_rmse: 4.3366 - learning_rate: 0.0010
Epoch 75/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 29.7105 - mae: 4.3204 - rmse: 5.4488 - val_loss: 18.3795 - val_mae: 3.6435 - val_rmse: 4.2871 - learning_rate: 5.0000e-04
Epoch 76/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 33.4175 - mae: 4.6416 - rmse: 5.7780 - val_loss: 19.0424 - val_mae: 3.7062 - val_rmse: 4.3638 - learning_rate: 5.0000e-04
Epoch 77/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 38.1371 - mae: 5.1111 - rmse: 6.1617 - val_loss: 19.8769 - val_mae: 3.7836 - val_rmse: 4.4584 - learning_rate: 5.0000e-04
Epoch 78/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 40.3934 - mae: 4.9940 - rmse: 6.3468 - val_loss: 19.6991 - val_mae: 3.7680 - val_rmse: 4.4384 - learning_rate: 5.0000e-04
Epoch 79/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 31.7810 - mae: 4.4576 - rmse: 5.6364 - val_loss: 18.8639 - val_mae: 3.6981 - val_rmse: 4.3433 - learning_rate: 5.0000e-04
Epoch 80/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 34.2114 - mae: 4.6918 - rmse: 5.8425 - val_loss: 17.9712 - val_mae: 3.6172 - val_rmse: 4.2392 - learning_rate: 5.0000e-04

In [ ]:
y_pred = model.predict(X_test).ravel()

print("\nError Cuadrático Medio (MSE):", mean_squared_error(y_test, y_pred))
print("Error Absoluto Medio (MAE):", mean_absolute_error(y_test, y_pred))
print("Coeficiente de Determinación (R²):", r2_score(y_test, y_pred))

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

Error Cuadrático Medio (MSE): 17.012945097327183
Error Absoluto Medio (MAE): 3.2785400295257574
Coeficiente de Determinación (R²): 0.6794250416462908

In [ ]:
def predict_one(sample: dict) -> float:

    # Convertir a DataFrame con columnas en orden esperado
    s = pd.DataFrame([sample])


    # Aplicar exactamente el mismo procesamiento
    s_proc = preprocess.transform(s[X.columns])
    s_proc = s_proc.astype(np.float32)

    # Predecir
    pred = model.predict(s_proc).item()
    return pred

In [ ]:
sample = {
    "hours_studied":7.0,
    "sleep_hours":8.0,
    "attendance_percent":75.5,
    "previous_scores":80.20,
}
pred = predict_one(sample)
print(f"Predecido {pred:.2f} ")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
Predecido 32.83